openapi: 3.0.0
info:
  title: Expense Tracker API
  version: 1.0.0
  description: Comprehensive OpenAPI documentation for the Expense Tracker RESTful
    API with hypermedia.
servers:
- description: Local development server
  url: http://127.0.0.1:5000/api
paths:
  /groups/:
    get:
      summary: List all groups
      tags:
      - Groups
      responses:
        '200':
          description: List of groups
          content:
            application/json:
              example:
                groups:
                - id: 101
                  name: Roommates
                  description: Shared apartment expenses
                  "@controls":
                    self:
                      href: /groups/101
                    update:
                      href: /groups/101
                      method: PUT
                    delete:
                      href: /groups/101
                      method: DELETE
                    members:
                      href: /groups/101/members/
                      method: GET
                    expenses:
                      href: /groups/101/expenses/
                      method: GET
                "@controls":
                  self:
                    href: /groups/
    post:
      summary: Create a new group
      tags:
      - Groups
      requestBody:
        required: true
        content:
          application/json:
            example:
              name: Roommates
              description: Shared apartment expenses
      responses:
        '201':
          description: Group created
        '400':
          description: Invalid input
        '404':
          description: Resource not found
        '415':
          description: "Unsupported Media Type \u2013 Use Content-Type: application/json"
  /groups/{group_uuid}:
    get:
      summary: Get group details
      tags:
      - Groups
      parameters:
      - $ref: '#/components/parameters/group_uuid'
      responses:
        '400':
          description: Invalid input
        '404':
          description: Resource not found
        '200':
          description: Successful response
          content:
            application/json:
              example:
                groups:
                - id: 101
                  name: Roommates
                  description: Shared apartment expenses
                  "@controls":
                    self:
                      href: /groups/101
                    update:
                      href: /groups/101
                      method: PUT
                    delete:
                      href: /groups/101
                      method: DELETE
                    members:
                      href: /groups/101/members/
                      method: GET
                    expenses:
                      href: /groups/101/expenses/
                      method: GET
                "@controls":
                  self:
                    href: /groups/
    put:
      summary: Update a group
      tags:
      - Groups
      parameters:
      - $ref: '#/components/parameters/group_uuid'
      requestBody:
        required: true
        content:
          application/json:
            example:
              name: Roommates
              description: Updated shared expenses
      responses:
        '200':
          description: Group updated
        '400':
          description: Invalid input
        '404':
          description: Resource not found
        '415':
          description: "Unsupported Media Type \u2013 Use Content-Type: application/json"
    delete:
      summary: Delete a group
      tags:
      - Groups
      parameters:
      - $ref: '#/components/parameters/group_uuid'
      responses:
        '400':
          description: Invalid input
        '404':
          description: Resource not found
        '204':
          description: Deleted successfully
  /groups/{group_uuid}/members/:
    get:
      summary: List all members in a group
      tags:
      - Members
      parameters:
      - $ref: '#/components/parameters/group_uuid'
      responses:
        '400':
          description: Invalid input
        '404':
          description: Resource not found
        '200':
          description: Successful response
          content:
            application/json:
              example:
                groups:
                - id: 101
                  name: Roommates
                  description: Shared apartment expenses
                  "@controls":
                    self:
                      href: /groups/101
                    update:
                      href: /groups/101
                      method: PUT
                    delete:
                      href: /groups/101
                      method: DELETE
                    members:
                      href: /groups/101/members/
                      method: GET
                    expenses:
                      href: /groups/101/expenses/
                      method: GET
                "@controls":
                  self:
                    href: /groups/
    post:
      summary: Add a member to a group
      tags:
      - Members
      parameters:
      - $ref: '#/components/parameters/group_uuid'
      requestBody:
        required: true
        content:
          application/json:
            example:
              user_id: 2
      responses:
        '201':
          description: Member added
        '400':
          description: Invalid input
        '404':
          description: Resource not found
        '415':
          description: "Unsupported Media Type \u2013 Use Content-Type: application/json"
  /groups/{group_uuid}/members/{user_uuid}:
    delete:
      summary: Remove a member from a group
      tags:
      - Members
      parameters:
      - $ref: '#/components/parameters/group_uuid'
      - $ref: '#/components/parameters/user_uuid'
      responses:
        '400':
          description: Invalid input
        '404':
          description: Resource not found
        '204':
          description: Deleted successfully
  /groups/{group_uuid}/expenses/:
    get:
      summary: List all expenses in a group
      tags:
      - Expenses
      parameters:
      - $ref: '#/components/parameters/group_uuid'
      responses:
        '400':
          description: Invalid input
        '404':
          description: Resource not found
        '200':
          description: List of expenses
          content:
            application/json:
              example:
                expenses:
                - id: 5001
                  amount: 200.5
                  description: March Electricity Bill
                  "@controls":
                    self:
                      href: /expenses/5001
                    update:
                      href: /expenses/5001
                      method: PUT
                    delete:
                      href: /expenses/5001
                      method: DELETE
                    participants:
                      href: /expenses/5001/participants/
                      method: GET
                    group:
                      href: /groups/101
                - id: 5002
                  amount: 95.75
                  description: Groceries
                  "@controls":
                    self:
                      href: /expenses/5002
                    update:
                      href: /expenses/5002
                      method: PUT
                    delete:
                      href: /expenses/5002
                      method: DELETE
                    participants:
                      href: /expenses/5002/participants/
                      method: GET
                    group:
                      href: /groups/101
                "@controls":
                  self:
                    href: /groups/101/expenses/
    post:
      summary: Create an expense in a group
      tags:
      - Expenses
      parameters:
      - $ref: '#/components/parameters/group_uuid'
      requestBody:
        required: true
        content:
          application/json:
            example:
              amount: 200.5
              description: March Electricity Bill
      responses:
        '201':
          description: Expense created
        '400':
          description: Invalid input
        '404':
          description: Resource not found
        '415':
          description: "Unsupported Media Type \u2013 Use Content-Type: application/json"
  /expenses/{expense_uuid}:
    get:
      summary: Retrieve a single expense
      tags:
      - Expenses
      parameters:
      - $ref: '#/components/parameters/expense_uuid'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: GET response example
        '400':
          description: Invalid input
        '404':
          description: Resource not found
    put:
      summary: Update an expense
      tags:
      - Expenses
      parameters:
      - $ref: '#/components/parameters/expense_uuid'
      requestBody:
        required: true
        content:
          application/json:
            example:
              amount: 210.0
              description: Updated Electricity Bill
      responses:
        '200':
          description: Expense updated
        '400':
          description: Invalid input
        '404':
          description: Resource not found
        '415':
          description: "Unsupported Media Type \u2013 Use Content-Type: application/json"
    delete:
      summary: Delete an expense
      tags:
      - Expenses
      parameters:
      - $ref: '#/components/parameters/expense_uuid'
      responses:
        '400':
          description: Invalid input
        '404':
          description: Resource not found
        '204':
          description: Deleted successfully
  /expenses/{expense_uuid}/participants/:
    get:
      summary: List participants of an expense
      tags:
      - Expenses
      parameters:
      - $ref: '#/components/parameters/expense_uuid'
      responses:
        '400':
          description: Invalid input
        '404':
          description: Resource not found
        '200':
          description: Successful response
          content:
            application/json:
              example:
                participants:
                - user_id: 1
                  share: 100.25
                  "@controls":
                    self:
                      href: /expenses/5001/participants/
                    user:
                      href: /users/1
                "@controls":
                  self:
                    href: /expenses/5001/participants/
                  add:
                    href: /expenses/5001/participants/
                    method: POST
    post:
      summary: Add a participant to an expense
      tags:
      - Expenses
      parameters:
      - $ref: '#/components/parameters/expense_uuid'
      requestBody:
        required: true
        content:
          application/json:
            example:
              user_id: 1
              share: 100.25
      responses:
        '201':
          description: Participant added
        '400':
          description: Invalid input
        '404':
          description: Resource not found
        '415':
          description: "Unsupported Media Type \u2013 Use Content-Type: application/json"
components:
  schemas:
    Links:
      type: object
      properties:
        self:
          type: object
          properties:
            href:
              type: string
        update:
          type: object
          properties:
            href:
              type: string
            method:
              type: string
        delete:
          type: object
          properties:
            href:
              type: string
            method:
              type: string
        members:
          type: object
          properties:
            href:
              type: string
            method:
              type: string
        expenses:
          type: object
          properties:
            href:
              type: string
            method:
              type: string
        participants:
          type: object
          properties:
            href:
              type: string
            method:
              type: string
        group:
          type: object
          properties:
            href:
              type: string
    Group:
      type: object
      required:
      - id
      - name
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        "@controls":
          $ref: '#/components/schemas/Links'
      example:
        id: 101
        name: Roommates
        description: Shared apartment expenses
        "@controls":
          self:
            href: /groups/101
          update:
            href: /groups/101
            method: PUT
          delete:
            href: /groups/101
            method: DELETE
          members:
            href: /groups/101/members/
            method: GET
          expenses:
            href: /groups/101/expenses/
            method: GET
    Expense:
      type: object
      required:
      - id
      - amount
      properties:
        id:
          type: string
        amount:
          type: number
        description:
          type: string
        "@controls":
          $ref: '#/components/schemas/Links'
      example:
        id: 5001
        amount: 200.5
        description: March Electricity Bill
        "@controls":
          self:
            href: /expenses/5001
          update:
            href: /expenses/5001
            method: PUT
          delete:
            href: /expenses/5001
            method: DELETE
          participants:
            href: /expenses/5001/participants/
            method: GET
          group:
            href: /groups/101
  parameters:
    expense_uuid:
      name: expense_uuid
      in: path
      required: true
      schema:
        type: string
    group_uuid:
      name: group_uuid
      in: path
      required: true
      schema:
        type: string
    user_uuid:
      name: user_uuid
      in: path
      required: true
      schema:
        type: string

